### ISSUE TITLE
Adding a BPNL (Legal to Legal) Hierarchy Structure in the Gate/Pool

### ISSUE THREAD

**Issue by rybtim** [eclipse-tractusx/sig-release#600] opened 2024-03-28 14:23 UTC
## Description
BPDM sharing members need to have the possibility of assigning multiple BPNLs to one overall 
BPNL in the portal as well as providing this information in the sharing process. This will serve as 
representation of the connection of a holding company and its subsidiaries.
The knowledge of the relations between legal Entities (BPNL) enables the system to assign specific 
information or documents to several related BPNLs simultaneously. Additionally, it can be used for 
reliable and comprehensive reporting. This reduces manual errors and increases process 
efficiency.
 
 
The Catena-X portal needs to receive the information regarding connection of BPNLs from the BPDM 
Pool. This is relevant for setting the correct roles and rights for the onboarding process. As an 
example, for certificate management there should be one master user who is allowed to upload the 
certificates for several BPNLs. The portal needs to have the functionality to maintain certificates 
(different feature) and to maintain user roles on a master admin level (different feature).
 
Different types of BPNL relations should be considered. The willingness to share this information 
and validity of information regarding claimed BPNL relations need to be ensured in the process. 
Business needs and requirements for Legal-to-Legal Hierarchies: 
• Re-supply to the backends of the individual companies (e.g. MDGs) must be feasible 
• Making hierarchies visible, even for SMEs 
• The compatibility of the data model is guaranteed 
• Hierarchies are not publicly available data and must be editable for the individual sharing 
members; data sovereignty lies with the data owner 
• To do this, IaaS providers must be able to change/create the hierarchies (Upsert API) 
• MVP minimal requirement, 1:n hierarchy level for the authorization concept in the portal with one 
link level (Muster AG: Muster Technology) BPNL-BPNL --> evaluate m:n relationships  
• currently "only" >50% shareholder shares represent n:1 relationships 
• Risk management can create correct risk assessments 
• Reduction of administrative effort in user management via an authorization concept in the portal 
• Contracts are concluded with the correct supplier (important in the event of insolvency) 
• Correct reports on, for example, sales with the supplier

Goals:
 
• Short-term goal, quick solution as PoC, simple visualization of single-level hierarchies à 
Eventually to be transferred into an app in the portal 
• Simultaneous start of evaluation of data model adaptation and process observation (proof that L 
is part of the company's own group) 
• Concept and first Mockups for visualization and own/existing BPDM data model 
• Implemented as a separate feature
  
Final conception for the topic of company hierarchies that takes into account all requirements of Portal, 
BPDM and EDC -> deriving necessary developments and adapting existing or creating new standards.

## Impact
- BPDM Gate and Pool API
- Portal

## Additional information 

- [ ] I'm willing to contribute to this feature

**Comment by jjeroch** [comment] 2024-04-01 19:35
Attention @rybtim  : **Upcoming PI Planning Preparation**

As we gear up for the forthcoming PI Planning session, it is crucial that all features under consideration align with our established Feature Quality Standards and Definition of Done (DoD) guidelines. To ensure your feature is thoroughly prepared and stands a strong chance of being prioritized, please provide comprehensive documentation that includes the following components:

1. Feature Summary: An executive overview that encapsulates the essence and objectives of the feature.
2. Change Description:
- High-Level Overview: A succinct synopsis of the proposed changes and their overarching impact.
- Detailed Analysis: An in-depth exploration of the specific alterations, including a clear exposition of the anticipated impact on existing systems.
3. Impacted Components: A list identifying all system components that will be affected by the feature implementation, accompanied by a brief explanation of the nature of the impact.
4. Acceptance Criteria: A set of clearly defined conditions that must be met for the feature to be considered complete and acceptable.
5. Test Scenarios: A detailed outline of test cases that cover all functional paths of the feature to ensure robust validation and verification.
6. Risks/Dependencies

Please note that any feature submissions lacking these essential elements will not be eligible for consideration in the upcoming PI Planning. It is imperative that your documentation is both thorough and precise to facilitate a smooth and effective planning process.

Please let me know in case you have any questions

**Comment by Grand-Thibault** [comment] 2024-04-03 12:29
@rybtim please add more description according to julias comment above

**Comment by jjeroch** [comment] 2024-04-03 19:06
Moved it back to "Inbox". In the current state there is no chance to discuss any implementation details at all. With that a committment is impossible

**Comment by rybtim** [comment] 2024-04-09 12:53
No implementation feature for R. 24.08. Handover to Expert Group plannend and moved to Inbox

**Comment by stephanbcbauer** [comment] 2024-04-11 10:41
As discussed in open planning, this feature will stay in Inbox until there is a handover to the related expert group. Please reach out, when the handover is done and the expert group is ready to work on the feature. Please also keep @jjeroch  [comment](https://github.com/eclipse-tractusx/sig-release/issues/600#issuecomment-2035378978) in mind.

Don't just start with the feature. Clarification is still needed. Same for:

- #599
- #643 
- #605  

Thx

**Comment by stephanbcbauer** [comment] 2024-04-11 10:51
@rybtim added you as assignee because we need a contact person for every feature.

**Comment by stephanbcbauer** [comment] 2024-04-11 10:58
Didn't think about it before, but since the feature is still in Inbox, the open decision label is not needed. Opinions?

**Comment by nicoprow** [comment] 2024-11-22 04:23
@rybtim I see this as a duplicate of #754. I will close this issue for now. If you think we should keep this issue open please contact me

**Closed by nicoprow** 2024-11-22 04:23 UTC
Labels: open decision, business partner, Prep-PI13
