### ISSUE TITLE
EDC - Concept for mutual credential verification

### ISSUE THREAD

**Issue by stefan-ettl** [eclipse-tractusx/sig-release#313] opened 2023-10-24 11:53 UTC
## Description

As a Data-Consumer who requires a certain credential in order to negotiate a specific Contract-Offer, I want to check if the Data-Provider as well owns those Credentials. As example, a credential points out if a partner signed a frame-agreement for a specific context or use-case. The Data-Provider simply specify this credential within a usage-policy to make sure, the Data-Consumer signed the agreement as well. 
However the data-consumer is currently not able to check this credential of the Data-Provider within the negotiation process. 

## Impact

For future scalability reasons of the network, a mutual verification of credential has to be established.

## Additional information 

- [ ] I'm willing to contribute to this feature

**Comment by lgblaumeiser** [comment] 2024-06-04 09:09
Removed from 24.05, as prerequisites are not fulfilled. Will be reconsidered later

**Comment by stephanbcbauer** [comment] 2024-07-12 08:27
Presented in the DRAFT Feature Freeze -> Committer is available

**Comment by lgblaumeiser** [comment] 2024-08-06 11:30
After an indepth discussion within the team, the requirement from Catena-X is not clear, as this mutual verification has not been demanded from anyone lately. Therefore, the issue is closed as not implemented.

**Closed by lgblaumeiser** 2024-08-06 11:30 UTC
Labels: edc, foss, Prep-R24.12
