### ISSUE TITLE
Enhancement Concept and Standardization of BP Predecessor/Successor

### ISSUE THREAD

**Issue by rybtim** [eclipse-tractusx/sig-release#601] opened 2024-03-28 14:27 UTC
## Description

I as a BPDM sharing member  want to have the functionality to mark a business partner (BPNL, BPNA or BPNS) as the successor or predecessor of another business partner (BPNL, BPNA or BPNS). This is relevant in case of mergers, acquisitions, etc.
 
The BPDM data model must  be enhanced with  a possibility for relating a business partner successor to a business partner predecessor, or the other way round. 
Example:
Company A is sold to Company B. The legal name of company A is dissolved but it is still relevant for former customers regarding e.g. warranty claims. Therefor there is a strong need to preserve the information about Company A and the linkage to Company B as legal successor and also vice versa (predecessor).
 
As this information is  currently not available in Catena-X  network there must be a concept worked out on how to provide this.  This concept must also reflect the aspects of data ownership (e.g. regarding maintenance of sites) as well as the impact  for linked  data objects (like dissolving existing relations between BPNL/S/A), an and requirement for components and functionalities:
- Consolidated Business requirements 
- CX BP data model enhancements
- Pool + GATE API enhancements (describe logic on how to provide and consume predecessor / successor relationships)
- CX Portal: BP data maintenance requirements (if applicable)
The results will be incorporated in the related standard  CX-0076, depending on the progress and resources also the technical implementation may be possible, leading to the adaption of standards CX-0012 + CX0074.
 
Outlook for further activities based on this concept (if not already covered in the points above) for Release 24.12:
 
## Technical realization of concept.
- Pool / Gate data model and APIs MUST be technically adapted + the data model and API enhancements MUST be included in the Pool and Gate API standardization documents CX-0012 + CX0074 
- Portal own company data maintenance UIs COULD be enhanced for enabling sharing member to maintain these relationships.

## Impact  for technical components (to be validated in the course of the concept work)
•             BPDM Gate and Pool API
•             Portal

## Additional information 

- [ ] I'm willing to contribute to this feature

**Comment by jjeroch** [comment] 2024-04-01 19:35
Attention @rybtim  : **Upcoming PI Planning Preparation**

As we gear up for the forthcoming PI Planning session, it is crucial that all features under consideration align with our established Feature Quality Standards and Definition of Done (DoD) guidelines. To ensure your feature is thoroughly prepared and stands a strong chance of being prioritized, please provide comprehensive documentation that includes the following components:

1. Feature Summary: An executive overview that encapsulates the essence and objectives of the feature.
2. Change Description:
- High-Level Overview: A succinct synopsis of the proposed changes and their overarching impact.
- Detailed Analysis: An in-depth exploration of the specific alterations, including a clear exposition of the anticipated impact on existing systems.
3. Impacted Components: A list identifying all system components that will be affected by the feature implementation, accompanied by a brief explanation of the nature of the impact.
4. Acceptance Criteria: A set of clearly defined conditions that must be met for the feature to be considered complete and acceptable.
5. Test Scenarios: A detailed outline of test cases that cover all functional paths of the feature to ensure robust validation and verification.
6. Risks/Dependencies

Please note that any feature submissions lacking these essential elements will not be eligible for consideration in the upcoming PI Planning. It is imperative that your documentation is both thorough and precise to facilitate a smooth and effective planning process.

Please let me know in case you have any questions

**Comment by Grand-Thibault** [comment] 2024-04-03 12:35
@rybtim please add more content to the description according to julias comment

**Comment by rybtim** [comment] 2024-04-09 12:51
No implementation feature for R. 24.08. Handover to Expert Group plannend and moved to Inbox

**Comment by stephanbcbauer** [comment] 2024-04-11 10:53
@rybtim added you as assignee because we need a contact person for every feature.

**Comment by stephanbcbauer** [comment] 2024-04-11 10:57
Didn't think about it before, but since the feature is still in Inbox, the open decision label is not needed. Opinions?

**Comment by stephanbcbauer** [comment] 2024-07-22 08:43
Discussed with @zygokaktus shouldnt be on Tractus-X

**Comment by zygokaktus** [comment] 2024-07-25 13:19
working session of 25.07.2024 can be found in CX BPDM Expert Grpup Sharepoint: 
https://bcgcatenax.sharepoint.com/:f:/r/sites/C-XNetworkServicesCommittee/Shared%20Documents/Expert%20Group%20-%20BPDM/Working%20sessions/Thursday?csf=1&web=1&e=6DGXih

**Comment by stephanbcbauer** [comment] 2024-08-08 06:19
@zygokaktus Can you please create an issue in your BPDM ExpertGoup Repository? and Copy the information into this issue? After this, we can delete this issue here in Tractus-X. Fine for you?

**Comment by zygokaktus** [comment] 2024-08-11 13:19
@stephanbcbauer: Why do you see it in tractus-X?  It is not relevant there (since it is concept work) but for the standards (i.e. Catena-X assoc,) it is, see: https://github.com/orgs/catenax-eV/projects/15/views/2?sliceBy%5Bvalue%5D=NSC

And it is linked there with this feature.: https://github.com/orgs/catenax-eV/projects/15/views/2?pane=issue&itemId=67960012 So from my point of view it is correct like it is right now? 
Or do you see it appear somewhere as being relevant for tractus-X? If so, it would be wrong, I agree.

**Comment by zygokaktus** [comment] 2024-09-19 11:50
Will be covered in the course of overall topic of relationships.
Idea is to establish a dedicated relationship type: "is replaced by" though it has already become obvious that this single relationship type will not cover all scenarios of predecessor/successor cases

**Comment by nicoprow** [comment] 2024-11-22 04:20
@rybtim This repo should be about working and planning specifiy issues. Planning a concept sounds to be something that should be tracked in the association board. Also, this feature just looks to me like a duplicate of #906. Is there a reason not to close this issue here?

**Comment by nicoprow** [comment] 2024-12-04 05:12
I will be closing this issue for now

**Closed by nicoprow** 2024-12-04 05:12 UTC
Labels: golden record, open decision, business partner, Prep-PI13
