### ISSUE TITLE
Simplify KA-EDC Deployment

### ISSUE THREAD

**Issue by TomBuchertTSystems** [eclipse-tractusx/sig-release#286] opened 2023-10-18 13:27 UTC
Benefit Hypothesis

    Maintaining three or more variants of the TX EDC charts is always behind the "state-of-the-art"
    Having a chart for the agent plane itself which can be plugged into an existing EDC umbrella is more practical

Beneficiaries

    any participant already deploying an EDC without agent
    any newly onboarding participant unsure which chart to use
    enablement providers who want to offer variants in a more easy fashion

Acceptance Criteria

    for each vault type, an agent-plane only chart which will register itself at the umbrella EDC
    samples for side-by-side deployment

Estimated Story Points:
10 SP

**Comment by drcgjung** [comment] 2023-10-19 12:50
# Story "Implement Data-Plane Chart"

Repository: https://github.com/eclipse-tractusx/knowledge-agents-edc

## Statement 

As a (potential) KA participant, I want the KA Agent Plane to be deployable alongside EDC charts such that I can seamlessly extend my existing EDC deployment.

## Acceptance Criteria

- find out how the dataplane can register/deregister itself in the control plane
- implement startup/teardown actions in the agent plane deployment
- make the agent plane chart refer to values in the umbrella chart
- extend the ct test 
- remove the old charts

## Estimation 

10 SP

**Comment by drcgjung** [comment] 2024-01-10 07:21
Duplicate of https://github.com/eclipse-tractusx/sig-release/issues/390

**Closed by drcgjung** 2024-01-10 07:21 UTC
Labels: Prep-PI11, foss, knowledge agent, Prep-PI12
