### ISSUE TITLE
EDC - Bi-directional transfers for Metadata (i.e. Feedback Channel)

### ISSUE THREAD

**Issue by stefan-ettl** [eclipse-tractusx/sig-release#624] opened 2024-04-03 07:35 UTC
As a Dataspace Participant consuming data from a data provider, I want to have a possibility to give feedback about the received data using the negotiated contract and its metadata.

Upstream EDC Some data sharing scenarios require both the provider and consumer to supply transfer metadata. Support the ability to exchange transfer metadata in a full-duplex fashion.

- [ ] Concept/Idea for "a Back Channel" has been created.

Initial creator: @jimmarino

**Comment by stephanbcbauer** [comment] 2024-04-11 07:13
Was presented in open planning ⇾ contributors and committer are involved.

**Comment by stephanbcbauer** [comment] 2024-06-05 06:43
Hello @stefan-ettl , @jimmarino , @lgblaumeiser 

Since the feature is a 24.08 feature and the development phase is coming to an end, we need a status on the feature.

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please check whether there is an assignment to a committee or expert group (supported-by) to be found on the [board](https://github.com/orgs/eclipse-tractusx/projects/26/views/28)
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.

If you need any clarification, please get in touch, thank you very much.
Stephan

**Comment by lgblaumeiser** [comment] 2024-06-11 10:51
@stephanbcbauer , this issue is not on the supported-by board mentioned above, I have not found any reason, why not, can you please have a check?

**Comment by lgblaumeiser** [comment] 2024-06-11 10:53
2024-06-11

* [x]  Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
* [x]  Please check whether the status (backlog, work in progress ...) is set correctly
* [ ]  Please check whether there is an assignment to a committee or expert group (supported-by) to be found on the [board](https://github.com/orgs/eclipse-tractusx/projects/26/views/28)
* [x]  Please comment on the current status of the feature:
         About to be started, as it is a concept, providing the result is not test relevant for the release
* [x]  Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.

**Comment by lgblaumeiser** [comment] 2024-06-25 12:18
Concept document will be ready with the Catena-X release

**Comment by lgblaumeiser** [comment] 2024-12-17 14:16
Duplicate of https://github.com/eclipse-tractusx/sig-release/issues/936

**Closed by lgblaumeiser** 2024-12-17 14:16 UTC
Labels: edc, Prep-PI13
