### ISSUE TITLE
[Product] PURIS FOSS Release Checks

### ISSUE THREAD

**Issue by tom-rm-meyer-ISST** [eclipse-tractusx/sig-release#589] opened 2024-03-27 15:28 UTC
> [!IMPORTANT]  
> Follow the [guidance on how to use the templates](https://github.com/eclipse-tractusx/sig-release/blob/main/README.md#release-management-acceptance-criteria).

## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.
Make sure to assign this issue to expert(s) for their approval, as soon as you have finished preparation. Multiple assignees allowed; they will un-assign themselves once review completed.

**Version to be included in Eclipse Tractus-X release**: 2.0.0

**Leading product repository:** [*repository link*](https://github.com/eclipse-tractusx/puris/)

# Compliance Verifications

This issue tracks all checks, that need to be performed for a product release in Eclipse Tractus-X. 

- [x] **Interoperability** checks performed
- [x] **Data Sovereignty** checks performed

# General Checks

- [x] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release)(TRGs) fulfilled https://github.com/eclipse-tractusx/puris/issues/363

> [!NOTE]
> Note: most criteria for documentation and security are now covered in TRGs

# Security Checks

- [x] **Thread Modelling Analysis** passed

# Test Results

- [x] **E2E Integration Test** passed
- [x] **User Journey** approved

# Helpful Links

- [Eclipse Tractus-X openAPI specs on SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)

cc: @PhillipNalesny @Ute-Burkhardt-Volkswagen

**Comment by tom-rm-meyer-ISST** [comment] 2024-05-03 11:06
Reviewing committer is @evegufy , thanks for taking that over!
I'll inform you in a couple of weeks once you can start with the review

**Comment by szymonkowalczykzf** [comment] 2024-05-13 05:56
Threat Modeling Approved. Changes reviewed, recommendations addressed & implemented.

**Comment by rauschg** [comment] 2024-05-13 07:28
User journey is confirmed by the BO role

**Comment by ThomasObermeyer** [comment] 2024-05-13 16:32
Reviewed interoperability requirements based on provided documentation.
Most changes in this release were due to Industry Core and EDC IATP changes, which are in full alignment with our interoperability architecture.

**@kelaja Approved!**

**Comment by RolaH1t** [comment] 2024-05-14 07:15
QG review 2024-05-14:
data sov in process, no blockers, but expect known known.
TRG ongoing in tandem with @evegufy; expect major version update to 2.0/3.0
Thread modelling completed; checkmark will be set once final PR merged (https://github.com/eclipse-tractusx/puris/pull/361)
Successful completion of tests expected in cw21
QG not approved / no further meeting scheduled.

**Comment by jjeroch** [comment] 2024-05-23 06:36
UI/UX Feedback:
Tested with “Fraunhofer Gesellschaft”  

 

**Overall**

Brief description at the top of each page describing content would be nice for better user experience. 

  

**Left Navigation Bar**

Please use different icon for Catalog, Negotiations, Transfers - currently all with  
<img width="39" alt="image" src="https://github.com/eclipse-tractusx/sig-release/assets/94133633/0b6585fb-047a-4eff-b356-40740063eaa9">


**Logout**

- Why does Logout button have a trash Symbol?  
<img width="229" alt="image" src="https://github.com/eclipse-tractusx/sig-release/assets/94133633/9b735a6c-b99b-4284-96bb-1be4db54d657">
=> **blocking** design not ok!!
 

  

- Unclear: upon clicking "Logout", nothing happens -> show as inactive  

 

 

 

##Dashboard Customer 
 
- DropDown Headers / Field Headers not correctly placed  
Also check all other views / data entry / filter screens. 

<img width="624" alt="image" src="https://github.com/eclipse-tractusx/sig-release/assets/94133633/9971d333-a474-4423-a542-268c2e80f88f">
 

  

- Dashboard currently has larger fond than all other Page Headers -> please unify 

  

- Create Demand - Day is mandatory and should require an asterix 

   

- Create Demand - Upon entering data and closing, SOME (not all) entries are preserved (and so are warnings for mandatory fields) --> upon closing and re-opening information should be reset to default  

  

- Similar for Create Delivery (here SOME entries are reset but warnings stay) 

 	 
<img width="331" alt="image" src="https://github.com/eclipse-tractusx/sig-release/assets/94133633/63afd03a-3dfc-4561-bff3-eda1d1268647">

=> **blocking** design not ok!!

 

## Stocks 

Switch between Material Stocks and Product Stocks 

--> suggest same layout adaption as for Dashboard Customer / Supplier View (see above) 

 
<img width="337" alt="image" src="https://github.com/eclipse-tractusx/sig-release/assets/94133633/528a3345-5c1c-4cbb-8585-4c2d3d09ab5e">

  

- Like the functionality that by clicking on a stock, data gets entered for add/update  

--> however, user needs better guidance to do this (else error prone to enter one slightly different attribute and Add instead of update) 

  

Proposal: Also would be good to have an update button right in the table to perform update.  

  

- Refresh -- update request has been sent successfully.  
Here, the process needs to be more transparent to the user. Not clear to which customer(s) what kind of data or request has been sent. 

<img width="685" alt="image" src="https://github.com/eclipse-tractusx/sig-release/assets/94133633/408f9807-43aa-42ff-9382-93dd1fe320b8">

  
## Catalog 

 

- Shown are Usage Policies (see Asset Action  

http://www.w3.org/ns/odrl/2/use   (Aus <https://puris-customer.int.demo.catena-x.net/catalog> ))  à is there a reason to call this “Asset condition(s)” rather than usage Policies? 

  

- Header: suggest to change header wording to avoid "EDC Catalog" but either "View Connector Catalog" or "View Partner Catalog" 

 

- No Action possible from this list - > unclear to user when and how user will consume such an offer 

 

- List shows a couple of items and item view takes up quite some space  

--> maybe consider using a table view instead to show more items in overview 

Similar for Negotiations View 

  

  

## Negotiations 

- Only Consumer Types available - why? Are there any other types foreseen? 

- To allow for better transparency suggest to include filter options, e.g. for State (Terminated, Finalized, ..), for Type, for BPN. 

  


 

## OTHER  

- Help Feature missing 

- Footer Component missing 


  

## Responsiveness 

Get Catalog with delay in loading results 

Upon clicking get Catalog, screen initially changes to “No Catalog available…” and then takes a couple of seconds to load the catalog items. 

 <img width="443" alt="image" src="https://github.com/eclipse-tractusx/sig-release/assets/94133633/d48783d7-03b6-466f-aa8c-641dc6150670">

**Comment by ReneSchroederLJ** [comment] 2024-05-23 09:18
@jjeroch 
Thank you for your valuable feedback. 

I have a question regarding one of your points. You mention that a footer component is missing. Can you elaborate on that? I couldn't find a reference to requirements for a footer component.

**Comment by evegufy** [comment] 2024-05-24 16:28
TRG review successfully completed

**Comment by KMA-2019** [comment] 2024-05-24 17:14
@vialkoje , @cbrugg , @tom-rm-meyer-ISST as aligned referencing here notes / feedback from **E2E Tests for Data Sovereignty.** No blocking issues for current Rel 24.05 but some items to be considered for next release(s). 
Some of the below have already been created as bugs, @tom-rm-meyer-ISST please map accordingly, thanks!

- User FrontEnd available: Role Company Admin is able to query catalogue and see negotiations and transfers
But company rules / policies **need to be configured upfront in backend** (via postman) to enable automatic contract negotiations, responsibility lies with Company Admin role 
--> add section in the User Manual describing this and the (legal) importance and responsibility behind defining these rules

- Currently **only one standard policy** per reg. connector / customer instance is supported (more precisely one for DTR, one for all submodels), negotiation happens automatically based on this 
--> enhance option to select partner and define specific policies (to be planned in context of BPDM Integration)
--> UI for specific configuration by dedicated role (e.g. Comp Admin) and more flexible policy configuration (without code changes) is needed  

- As a **non-Admin user** I do not have ability to view policies in detail --> transparency for users when interacting with and requesting / consuming data via dashboard / views on underlying usage policies to be enhanced
 
- ContractReference Constraint or **configuration of policies specific to one partner only** not implemented --> clarification of potential reference to "PURIS standard contract" and enabling of ContractReference for 24.08.

- unclear meaning of different stati in negotations --> add view of **successfull contract agreeements** wrt which data have been closed

- current logging only done on info level --> enhance **logging of policies** (currently only available at debug level)

- in case of non-matching policies (tested in various scenarios) no negotiation takes place --> ** enhance visualization or specific Error message to user**

- **no validation of the Schema** "profile": "cx-policy:profile2405" (required to ensure interop with other PURIS apps) 

- **User guide** states in Negotiations Section: "Note: Per data request per partner, there are two Negotiations as one contracts the partner's request asset and the partner contracts the user's response asset." --> needs update to current process

**Comment by RolaH1t** [comment] 2024-05-25 07:20
Congrats for crossing the finish line:
Quality Gate fully approved with all necessary pre-requisites fulfilled!
Thanks for all your efforts,
Roland

**Comment by jjeroch** [comment] 2024-05-27 18:03
> @jjeroch Thank you for your valuable feedback.
> 
> I have a question regarding one of your points. You mention that a footer component is missing. Can you elaborate on that? I couldn't find a reference to requirements for a footer component.

Hi @ReneSchroederLJ  it is not a hard requirement but a "feature" which usually comes with an app to manage Terms, Privacy, Cookies etc.

**Comment by KMA-2019** [comment] 2024-05-28 13:05
Hi @tom-rm-meyer-ISST , @ReneSchroederLJ , cc: @jjeroch
Regarding UUX findings please see the retest results:

- All items not mentioned below have been retested successfully. 
- Still open are the following, all of which except the commented are followed up in Changelog as KnownKnowns. 
- I did notice two more things - marked with ++ below - would be nice if those could be taken into consideration for ChangeLog as well. 

Thanks!

@jjeroch can you please review and decide about granting final approval.

----------------------------------------------------------------------------------------------------------------------------------------
**Overall**

> Brief description at the top of each page describing content would be nice for better user experience.

--> Changelog

**Dashboard Customer**

> Create Demand - Upon entering data and closing, SOME (not all) entries are preserved (and so are warnings for mandatory fields) --> upon closing and re-opening information should be reset to default

--> Changelog
 
**++** Also noticed that UOM Field has different opening behaviour, suggest to keep empty with "select unit" also for "Create Demand" :  
Create Demand 
![image](https://github.com/eclipse-tractusx/sig-release/assets/60438746/8a6f7b4e-b527-4e1c-a5f8-72faa6110922)
Add Delivery
![image](https://github.com/eclipse-tractusx/sig-release/assets/60438746/fd1ab15b-288d-48ee-9a79-b36d72c922b4)

**Stocks**

> Switch between Material Stocks and Product Stocks
> --> suggest same layout adaption as for Dashboard Customer / Supplier View

Not changed but also not in ChangeLog -> OK from my side,

> Like the functionality that by clicking on a stock, data gets entered for add/update
> --> however, user needs better guidance to do this (else error prone to enter one slightly different attribute and Add instead of update)
> Proposal: Also would be good to have an update button right in the table to perform update.

--> ChangeLog

> Refresh -- update request has been sent successfully.
> Here, the process needs to be more transparent to the user. Not clear to which customer(s) what kind of data or request has been sent.

--> ChangeLog

**Catalog**
> No Action possible from this list - > unclear to user when and how user will consume such an offer

--> ChangeLog

**++** Also noticed that it is possible to select a row - and not able to deselect by clicking anywhere else.
 
![image](https://github.com/eclipse-tractusx/sig-release/assets/60438746/2028c879-222b-423e-a14b-6d6d61e206eb)

**Negotiations**
> To allow for better transparency suggest to include filter options, e.g. for State (Terminated, Finalized, ..), for Type, for BPN.

--> ChangeLog

**Other**

> Help Feature missing 

User Guide available not, not a general help section -> OK from my side

> Footer Component missing

User Guide, About and Copyright Info are now available on each page -> OK from my side

**Comment by tom-rm-meyer-ISST** [comment] 2024-05-28 13:54
> Create Demand - Upon entering data and closing, SOME (not all) entries are preserved (and so are warnings for mandatory fields) --> upon closing and re-opening information should be reset to default

Thanks for your feedback. I updated the [Release's Changelog](https://github.com/eclipse-tractusx/puris/releases/tag/2.0.1) accordingly.

**Closed** 2024-06-20 04:36 UTC
Labels: foss, puris
