### ISSUE TITLE
Knowledge Agents 24.12 Release Checks 

### ISSUE THREAD

**Issue by obalandi** [eclipse-tractusx/sig-release#902] opened 2024-10-10 12:15 UTC
## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.
Make sure to assign this issue to expert(s) for their approval, as soon as you have finished preparation. Multiple assignees allowed; they will un-assign themselves once review completed.

**Responsible contacts**:

- Committer: @almadigabor 
- ExpertGroup: @Grand-Thibault (Behaviroal Twin Expert Group)
- Contributor contact: @obalandi, @drcgjung 

**Version to be included in Eclipse Tractus-X release**:

- App version: 1.14.24
- Helm Chart version: 1.14.24

**Leading product repository:** [*repository link*](https://github.com/eclipse-tractusx/knowledge-agents)

## Compliance

- [ ] Possible changes (through the new features) on related Catena-X standards are considered and addressed
- [x] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release)(TRGs) fulfilled

- https://github.com/eclipse-tractusx/knowledge-agents/issues/169 
- https://github.com/eclipse-tractusx/knowledge-agents-edc/issues/248 
- https://github.com/eclipse-tractusx/knowledge-agents-aas-bridge/issues/102 

Make sure to open and fill in a separate **documentation issue** in your product repository using the [Quality Gate Checklist issue template](https://github.com/eclipse-tractusx/.github/blob/main/.github/ISSUE_TEMPLATE/qg-checklist.md)

> [!NOTE]
> Note: most criteria for documentation and security are now covered in TRGs

## Functionality

- [ ] Feature works as expected and described
- [ ] Backward compatibility maintained (depending Major/ Minor) 

## Performance

- [ ] Memory and CPU usage is within acceptable limits oriented with goldilocks 

## Testing

- [ ] Unit tests cover all new features
- [ ] Integration tests are updated
- [ ] E2E/Integration test passed
- [ ] Regressions tests passed

## Feature summary

Please provide a list of all features that have been developed in the current phase. This list is essential for several reasons:

- **Test Preparation:** Identifying new features will help in the creation of new end-to-end (E2E) tests and ensure that the relevant aspects are thoroughly tested.
- **Awareness:** It will raise awareness of the features that need to be prioritized during the testing process.
- **Board Management:** This will assist in keeping the project board organized and up-to-date.

By documenting these features, you will contribute to a smoother and more efficient release process.

> [!NOTE]
> Note: all features needs to be closed to get approval for release

| Feature | Test Status | Note |
|----------|----------|----------|
| [Update of the Knowledge Agents to tractusx-edc 0.8.0](https://github.com/eclipse-tractusx/knowledge-agents/issues/168) | Done|   |

## Release Documentation

- [ ] Release notes/Changelogs are updated
- [ ] Migration scripts/documentation are included if necessary (Ensure that any database or infrastructure migrations are included).
- [ ] Known knowns

## Summary

Please provide a short summary about the new values/benefits of the new features here:

- Update of the Knowledge Agents to tractusx-edc 0.8.0

## Helpful Links

- [Eclipse Tractus-X openAPI specs on SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)

**Comment by ther3sa** [comment] 2024-11-18 18:33
**QG Review**

- To ensure transparency, could you please check off any topics that have already been worked on or completed?
- I was wondering if there are no 'Known Knowns' for this issue?  

Thank you for your help!

**Comment by ther3sa** [comment] 2024-11-27 16:41
Hi @almadigabor , @Grand-Thibault , @obalandi, @drcgjung,
Could you give me an update about this Release check issue?

**Comment by obalandi** [comment] 2024-11-28 08:01
> Test Management review: App version 1.14.24 as described in Release Info section was tested and the Integration/E2E tests passed, as documented in detail in issue [eclipse-tractusx/knowledge-agents#168](https://github.com/eclipse-tractusx/knowledge-agents/issues/168)
> 
> Release Check section on "Testing" above thus considered to be successful. Thanks for your efforts.
> 
> Follow-up questions for clarification:
> 
> * Is Knowledge Agents still deployed on the Catena-X INT environment or was this only done for testing? I am not seeing the app reported in ArgoCD at the moment in a "product-knowledge-agents" namespace. Or maybe I am looking in the wrong path, as there e.g. seem to be KA components used by DPP wallet?
> * By now EDC 0.8.0-RC6 was published. Tests were run for 0.8.0-RC4 as the version available at time of testing. Do you plan to also make this update for the 24.12 release, or only continue upgrading for 25.3? Would there be a way for you to quickly test the continued functionality with the latest EDC release?

Unfortunately, we do not have the capacity to run the integration and the E2E tests with release 0.8.0-RC6. We are currently working on the release deployment based on the final EDC version. Basic tests are performed automatically.

**Comment by ther3sa** [comment] 2024-11-28 11:20
> > Test Management review: App version 1.14.24 as described in Release Info section was tested and the Integration/E2E tests passed, as documented in detail in issue [eclipse-tractusx/knowledge-agents#168](https://github.com/eclipse-tractusx/knowledge-agents/issues/168)
> > Release Check section on "Testing" above thus considered to be successful. Thanks for your efforts.
> > Follow-up questions for clarification:
> > 
> > * Is Knowledge Agents still deployed on the Catena-X INT environment or was this only done for testing? I am not seeing the app reported in ArgoCD at the moment in a "product-knowledge-agents" namespace. Or maybe I am looking in the wrong path, as there e.g. seem to be KA components used by DPP wallet?
> > * By now EDC 0.8.0-RC6 was published. Tests were run for 0.8.0-RC4 as the version available at time of testing. Do you plan to also make this update for the 24.12 release, or only continue upgrading for 25.3? Would there be a way for you to quickly test the continued functionality with the latest EDC release?
> 
> Unfortunately, we do not have the capacity to run the integration and the E2E tests with release 0.8.0-RC6. We are currently working on the release deployment based on the final EDC version. Basic tests are performed automatically.

@ds-hzimmer ?

**Comment by ther3sa** [comment] 2024-11-29 11:02
@obalandi, @drcgjung @almadigabor 

To ensure transparency, could you please check off any topics that have already been worked on or completed?

**Comment by ther3sa** [comment] 2024-11-29 15:56
Hi @almadigabor,
we want to release on Monday 2.12. 
Is it possible to perform the QG checks for Knowledge Agents until Monday(2.12) morning?

**Comment by almadigabor** [comment] 2024-12-02 09:48
I try to get ready until noon. Here are the releases so far. We'll have 1 more release, just need to address a Trivy finding. I'll post it here as well.

https://github.com/eclipse-tractusx/knowledge-agents-edc/releases/tag/v1.14.24
https://github.com/eclipse-tractusx/knowledge-agents-aas-bridge/releases/tag/v1.14.24

**Comment by almadigabor** [comment] 2024-12-03 14:29
I've closed all 3 QGs, as every open issue have been addressed.

**Comment by almadigabor** [comment] 2024-12-04 09:00
Hey @obalandi, could you please have a look at the remaining unchecked boxes in this issue and mark everything that's done? We'll be able to close this issue then.

**Comment by drcgjung** [comment] 2024-12-04 09:11
Since Oz is OOO today and only returning tomorrow (and since I can not tick the checkmarks in his ticket), here my status report:
- [x]  No changes on related Catena-X standards are considered and addressed (just a maintenance feature)
- [x]  Feature works as expected and described (just a maintenance feature)
- [x]  Backward compatibility maintained (existing features are completely supported/maintained)
- [x]  Memory and CPU usage is within acceptable limits oriented with goldilocks (default values are minimal for chart testing, recommendations for practical applications from the integration tests in the charts/admin guide)
- [x] Unit tests cover all new features (only maintenance)
- [x]  Integration tests are updated (only maintenance)
- [x]  E2E/Integration test passed (see report)
- [x]  Regressions tests passed (part of the test suite, see report)
- [x] Release notes/Changelogs are updated
- [x] Migration scripts/documentation are included if necessary (state is provided by other components, such as EDC).
- [x] Known knowns (documents as open issues in the repository)

**Comment by ther3sa** [comment] 2024-12-04 09:39
Based on the above checks, I can approve this issue. 

Congrats 🎉
 Quality Gate fully approved with all necessary pre-requisites fulfilled!
  Thank you for all your efforts :)

**Closed by ther3sa** 2024-12-04 09:39 UTC
Labels: knowledge agent, Prep-R24.12
